### ISSUE TITLE
Package Versions

### ISSUE THREAD

**Issue by just-anotherlurker** [rish-av/gan_spectral_matching#1]
Hello,
I am looking to replicate your networks for synthesising images from different spectra but I have not been able to do so yet. Could you please let me know what versions of packages you used during the training and testing?
Best wishes and thanks in advance,
JAL

**Comment by rish-av** [comment]
Yes sure, I will add a requirements.txt file which you can use to train the network.

**Comment by rish-av** [comment]
@just-anotherlurker Added the requirements file, sorry for the very late reply, was busy in some work, let me know if it works now.

**Comment by just-anotherlurker** [comment]
@rish-av  
Many thanks, and no need to apologise. I will use these versions of the packages and see if I can replicate your results.
Best wishes,
JAL
